# Generated by Django 3.0.2 on 2020-01-16 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(default=datetime.datetime(2020, 1, 16, 9, 19, 56, 173969, tzinfo=utc), upload_to='uploads/', verbose_name='heloo')),
                ('data_bin', models.BinaryField(default=b'', max_length=1000, verbose_name='your file')),
            ],
        ),
    ]
