# Generated by Django 3.0.2 on 2020-01-16 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_file',
            field=models.FileField(default=datetime.datetime(2020, 1, 16, 9, 20, 17, 671061, tzinfo=utc), upload_to='uploads/', verbose_name='heloo'),
        ),
    ]
