# Generated by Django 3.0.2 on 2020-01-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20200116_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='knn',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='svm',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='tree',
        ),
    ]
